# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "policy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "policy.name" . }}
    chart: {{ template "policy.chart" . }}
    component: "policy"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
