# Copyright Contributors to the Open Cluster Management project

fullnameOverride: null
nameOverride: null

org: open-cluster-management
replicas: 1

args:
  frequency: 30
  verbosity: 0

securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true

clusterName: null
clusterNamespace: ""

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node.kubernetes.io/not-ready
  operator: Exists
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

global:
  imagePullPolicy: IfNotPresent
  imagePullSecret: null
  imageOverrides:
    iam_policy_controller: quay.io/open-cluster-management/iam-policy-controller:latest-2.5
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
