# Copyright Contributors to the Open Cluster Management project

fullnameOverride: null
nameOverride: null

org: open-cluster-management

enabled: true
hubKubeconfigSecret: config-policy-controller-hub-kubeconfig

clusterName: null
clusterNamespace: null

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 512Mi

affinity: {}

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "infra"
  effect: "NoSchedule"
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

global: 
  imagePullPolicy: Always 
  imagePullSecret: null
  imageOverrides: 
    config_policy_controller: quay.io/open-cluster-management/config-policy-controller:edge
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
