apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: config-policy-controller
rules:
# Rules for maintaining the lease on the hub
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - config-policy-controller
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
