# Copyright Contributors to the Open Cluster Management project

fullnameOverride: null
nameOverride: null

org: open-cluster-management
replicas: 1
args:
  frequency: 30
  verbosity: 0
  defaultDuration: null
securityContext:
  pod:
    runAsNonRoot: true
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    privileged: false

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node.kubernetes.io/not-ready
  operator: Exists
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

clusterName: null

global:
  imagePullPolicy: IfNotPresent
  imagePullSecret: null
  imageOverrides:
    cert_policy_controller: quay.io/open-cluster-management/cert-policy-controller:latest-2.5
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
